### ISSUE TITLE
Failure case of https://tripgo.skedgo.com/satapp/booking

### ISSUE THREAD

**Issue by thuytrinh** [skedgo/tripgo-api#25]
We're trying to deal with the case that users haven't signed up yet. In that case, what will the `booking` return? We didn't see any relevant information on https://skedgo.github.io/tripgo-api/ yet. We've seen different JSON responses. So, in order to make things clear and consistent, can you guys please update https://skedgo.github.io/tripgo-api/?

**Comment by MarianoTucat** [comment]
documentation updated in https://skedgo.github.io/tripgo-api/#tag/Booking-Beta%2Fpaths%2F~1booking%2Fget

Note that the response code is still 200, but swagger does not allow two definitions for the same error code. I would prefer to return a proper error code instead of 200 in thit case, but this is implemented in that way following a previous requirement of the android team.

**Comment by thuutin** [comment]
> I would prefer to return a proper error code instead of 200 in this case

@MarianoTucat How much effort is required to instead returning a proper error code?

**Comment by MarianoTucat** [comment]
not much at all, I can easily change all the booking errors to, instead of return a `200` return the proper code, but we need to make sure that change won't break the apps, both Android and iOS

**Comment by pnuts2** [comment]
Just caught up with this issue. So, @MarianoTucat , did you end up making any changes?

**Comment by MarianoTucat** [comment]
no
